import csv

data = [
    ["question", "answer"],
    ["How many PTO days do we get each year?", "18"],
    ["What is the home-office stipend for new hires?", "$500"],
    ["Can I choose between a Mac and a PC?", "MacBook Pro and Dell XPS"],
    ["Do I need a receipt for a $50 meal?", "No"],
    ["Is alcohol reimbursable?", "No"],
    ["When is payday?", "Biweekly on Fridays"],
    ["When are timesheets due?", "Mondays by 10:00 AM"],
    ["What are the core collaboration hours?", "10:00 AM to 4:00 PM"],
    ["When do medical benefits start?", "First of the month after hire"],
    ["What is the 401(k) match?", "4%"],
    ["How many weeks of parental leave?", "16"],
    ["How quickly report a lost laptop?", "24 hours"],
    ["What is the learning stipend?", "$1,000"],
    ["What are work hours?", "9:00 to 17:30"],
    ["Can I carry over PTO?", "5 days"],
    ["What is the bereavement policy?", "5 days"],
    ["Who report harassment to?", "Manager or HR"],
    ["What laptop encryption?", "Full-disk"],
    ["Are conferences reimbursable?", "Yes"],
    ["Does company pay 100% insurance?", "No, 80%"],
    ["What happens during offboarding?", "Return assets"],
    ["Is remote work allowed?", "Yes"],
    ["What is the travel policy?", "Economy airfare"],
    ["Is MFA required?", "Yes"],
    ["Can I use personal cloud?", "No"],
    ["Where are handbook updates?", "Knowledge Base"],
    ["Is 401k vesting immediate?", "Yes"],
    ["Are bonuses paid with payroll?", "Yes"],
    ["Ergonomic assessment?", "Yes"],
    ["Response time for requests?", "1 business day"],
    ["How long are meetings?", "50 mins or less"],
    ["When is the review cycle?", "Q1"],
    ["What is the leveling range?", "L1 to L7"],
    ["Who determines exempt status?", "Role and law"],
    ["What is the overtime rate?", "1.5x"],
    ["How long is the meal break?", "30 minutes"],
    ["Privacy screen policy?", "Required during travel"],
    ["Are investigations confidential?", "Yes"],
    ["When disclose conflicts?", "Immediately"],
    ["Is retaliation forbidden?", "Yes"],
    ["What are company values?", "Integrity and transparency"],
    ["Is handbook a contract?", "No"],
    ["Where are hotel caps?", "Travel portal"],
    ["Can I book business class?", "Only over 6 hours"],
    ["Are vision benefits included?", "Yes"],
    ["First disciplinary step?", "Coaching or warnings"],
    ["Laptop repair?", "Via IT"],
    ["Is jury duty paid?", "Yes"],
    ["Payroll frequency?", "Biweekly"]
]

with open('hr_data_50.csv', 'w', newline='') as file:
    writer = csv.writer(file, quoting=csv.QUOTE_ALL)
    writer.writerows(data)

print("✅ Step 1: 'hr_data_50.csv' created.")