import dspy
import mlflow


MY_GROQ_API_KEY = ""

mlflow.set_tracking_uri("sqlite:///mlflow.db")
mlflow.set_experiment("Manual_Native_Tools")
mlflow.dspy.autolog()


lm = dspy.LM(
    model="groq/llama-3.3-70b-versatile", 
    api_key=MY_GROQ_API_KEY
)

adapter = dspy.ChatAdapter(use_native_function_calling=True)
dspy.configure(lm=lm, adapter=adapter)

class ToolSignature(dspy.Signature):
    """Analyze the query and decide which tools to call using native function calling."""
    query: str = dspy.InputField()
    tools: list[dspy.Tool] = dspy.InputField()
    tool_calls: dspy.ToolCalls = dspy.OutputField()


def verify_scam(query: str) -> str:
    """Verifies if a message is a known scam in India."""
    return f"Result: Match found for '{query}' in the 2026 Fraud Database."


available_tools = [dspy.Tool(verify_scam)]

# 6. Initialize Predictor
predictor = dspy.Predict(ToolSignature)

# 7. The Manual Execution Loop
if __name__ == "__main__":
    with mlflow.start_run(run_name="Manual_Execution_Run"):
        # Step A: Request tool calls from the model
        prediction = predictor(
            query="Verify this: 'You won a lottery of 1 Cr from KBC, click here.'",
            tools=available_tools
        )

        # Step B: Iterate and execute
        # If tool_calls exists, loop through them
        if prediction.tool_calls:
            for call in prediction.tool_calls:
                # Robust attribute access (handles both object and tuple returns)
                name = getattr(call, 'name', call[0] if isinstance(call, tuple) else None)
                args = getattr(call, 'args', call[1] if isinstance(call, tuple) else None)
                
                print(f"🛠️  Model called: {name}")
                print(f"📦 Arguments: {args}")
                
                # Step C: Execute the logic
                # Option 1: Use the built-in execute (requires tool registration)
                # Option 2: Manual call
                if name == "verify_scam":
                    output = verify_scam(**args)
                    print(f"✅ Tool Output: {output}")
        else:
            print("No tool calls generated by the model.")

    print("\n🚀 Run 'mlflow ui' and check the 'Traces' tab to see the native JSON!")